# Importer l'image de base à partir du docker hub de "node:12.11.0" as build 
----------

#créer un repertoire /app comme working directory 
--------


COPY package*.json ./

#effectuer l'installation des packets et des dépendances 
------------ 

COPY . ./

# Arguments
ARG configuration=production

# Build the application
RUN npm run build -- --outputPath=./dist/out --configuration $configuration





#### Stage 2, use the compiled app, ready for production with Nginx

#importer l'image de base de nginx 
FROM nginx

# Copy the angular build from Stage 1
COPY --from=build /app/dist/out/ /usr/share/nginx/html

# Copy our custom nginx config
COPY /nginx-custom.conf /etc/nginx/conf.d/default.conf


# Expose port 80 to the Docker host, so we can access it
# from the outside.
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
